<?php
/**
 * MIT License
 *
 * Copyright (c) 2018 PHP DLX
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NON INFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */


use Vilex\Templates\AbstractTemplate;

/** @var AbstractTemplate $this */

$pagina_atual = $this->getAtributo('pagina-atual');
$qtde_registros_pagina = $this->getAtributo('qtde-registros-pagina');
$qtde_registros_atual = $this->getAtributo('qtde-registros-lista');
?>

[CORPO]
<div class="box-paginacao">
    <?php if ($pagina_atual === 1) : ?>
        <a href="javascript:" class="botao-pagina -anterior --desativado">
            Anterior
        </a>
    <?php else : ?>
        <a href="javascript:" onclick="irParaPagina(<?php echo $pagina_atual  - 1 ?>)" class="botao-pagina -anterior">
            Anterior
        </a>
    <?php endif; ?>

    <?php if ($qtde_registros_atual < $qtde_registros_pagina) : ?>
        <a href="javascript:" class="botao-pagina -proxima --desativado">
            Próxima
        </a>
    <?php else : ?>
        <a href="javascript:" onclick="irParaPagina(<?php echo $pagina_atual + 1 ?>)" class="botao-pagina -proxima">
            Próxima
        </a>
    <?php endif; ?>
</div>
[/CORPO]
