<?php
/**
 * MIT License
 *
 * Copyright (c) 2018 PHP DLX
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NON INFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

use PainelDLX\Domain\GruposUsuarios\Entities\GrupoUsuario;
use PainelDLX\Domain\PermissoesUsuario\Entities\PermissaoUsuario;
use Vilex\Templates\AbstractTemplate;

/**
 * @var AbstractTemplate $this
 */

/** @var PermissaoUsuario $permissao_usuario */
$permissao_usuario = $this->getAtributo('permissao-usuario');
?>

[CORPO]
<h1 class="titulo-pagina"><?php echo $this->getAtributo('titulo-pagina') ?></h1>

<details class="detalhe-registro" open>
    <summary class="detalhe-registro-titulo">Geral</summary>

    <p class="detalhe-registro-paragr">
        <span class="detalhe-registro-rotulo">Alias</span>
        <?php echo $permissao_usuario->getAlias() ?>
    </p>

    <p class="detalhe-registro-paragr">
        <span class="detalhe-registro-rotulo">Descrição</span>
        <?php echo $permissao_usuario->getDescricao() ?>
    </p>
</details>

<details class="detalhe-registro" open>
    <summary class="detalhe-registro-titulo">Grupos de Usuários</summary>

    <p class="mensagem-usuario -info">
        Grupos de Usuários que possuem essa permissão.
    </p>

    <?php if (!$permissao_usuario->getGrupos()->count()) : ?>
        <p class="sem-registros">Nenhum grupo de usuário com essa permissão.</p>
    <?php else : ?>
        <ul class="lista-grupos-permissoes">
            <?php
            /** @var GrupoUsuario $grupo_usuario */
            foreach ($permissao_usuario->getGrupos() as $grupo_usuario) : ?>
                <li class="grupo"><?php echo $grupo_usuario->getNome() ?></li>
            <?php endforeach; ?>
        </ul>
    <?php endif; ?>
</details>
[/CORPO]