<?php
/**
 * MIT License
 *
 * Copyright (c) 2018 PHP DLX
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NON INFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

use Vilex\Templates\AbstractTemplate;

/**
 * @var AbstractTemplate $this
 */
?>

[CORPO]
<h1 class="titulo-pagina">{{ titulo-pagina }}</h1>

<form id="form-permissao" method="post" action="/painel-dlx/permissoes/criar-nova-permissao">
    <fieldset class="form-grupo">
        <legend class="form-titulo">Geral</legend>

        <p class="form-paragr">
            <label for="txt-alias" class="form-rotulo form-controle-alias">Alias</label>
            <input type="text" name="alias" id="txt-alias" maxlength="50" class="form-controle" required>
        </p>

        <p class="form-paragr">
            <label for="txt-descricao" class="form-rotulo form-controle-descricao">Descrição</label>
            <input type="text" name="descricao" id="txt-descricao" maxlength="150" class="form-controle" required>
        </p>
    </fieldset>

    <p class="form-botoes">
        <button type="submit" class="botao-salvar" data-ajax-msg="Criando nova permissão.<br>Por favor aguarde...">
            Salvar
        </button>
    </p>
</form>
[/CORPO]

[SCRIPTS]
<script>
    $('#form-permissao').formAjax({
        func_depois: function (json, form, xhr) {
            if (json.retorno === 'sucesso') {
                msgUsuario.adicionar(json.mensagem, json.retorno, xhr.id);
                window.location = '/painel-dlx/permissoes/editar?permissao_usuario_id=' + json.permissao_usuario_id;
                return;
            }

            msgUsuario.mostrar(json.mensagem, json.retorno, xhr.id);
        }
    });
</script>
[/SCRIPTS]