<?php
/**
 * MIT License
 *
 * Copyright (c) 2018 PHP DLX
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NON INFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

use PainelDLX\Domain\PermissoesUsuario\Entities\PermissaoUsuario;
use Vilex\Templates\AbstractTemplate;

/**
 * @var AbstractTemplate $this
 */

/** @var PermissaoUsuario $permissao_usuario */
$permissao_usuario = $this->getAtributo('permissao-usuario');
?>

[CORPO]
<h1 class="titulo-pagina">{{ titulo-pagina }}</h1>

<form id="form-permissao" method="post" action="/painel-dlx/permissoes/editar-permissao">
    <input type="hidden" name="permissao_usuario_id" value="<?php echo $permissao_usuario->getId() ?> ">

    <fieldset class="form-grupo">
        <legend class="form-titulo">Geral</legend>

        <p class="form-paragr">
            <label for="txt-alias" class="form-rotulo">Alias</label>
            <?php echo $permissao_usuario->getAlias() ?>
            <span class="dica-geral" data-texto="Após a criação da permissão ela pode ser solicitada em alguma funcionalidade do sistema para verificação da autorização do usuário. Alterá-la pode fazer com que o sistema deixe de funcionar corretamente.">
                (por que não posso alterar?)
            </span>
        </p>

        <p class="form-paragr">
            <label for="txt-descricao" class="form-rotulo form-controle-descricao">Descrição</label>
            <input type="text" name="descricao" id="txt-descricao" value="<?php echo $permissao_usuario->getDescricao() ?>" maxlength="150" class="form-controle" required>
        </p>
    </fieldset>

    <p class="form-botoes">
        <button type="submit" class="botao-salvar" data-ajax-msg="Salvando permissão.<br>Por favor aguarde...">
            Salvar
        </button>
    </p>
</form>
[/CORPO]

[SCRIPTS]
<script>
    $('#form-permissao').formAjax({
        func_depois: function (json, form, xhr) {
            msgUsuario.mostrar(json.mensagem, json.retorno, xhr.id);
        }
    });
</script>
[/SCRIPTS]