<?php
/**
 * MIT License
 *
 * Copyright (c) 2018 PHP DLX
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NON INFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

use PainelDLX\Domain\CadastroUsuarios\Entities\GrupoUsuario;
use PainelDLX\Domain\CadastroUsuarios\Entities\Usuario;
use Vilex\VileX;

/**
 * @var VileX $this
 */

/** @var Usuario $usuario */
$usuario = $this->getAtributo('usuario');
?>

[CORPO]
<h1 class="titulo-pagina"><?php echo $this->getAtributo('titulo-pagina') ?></h1>

<form id="form-alterar-senha" method="post" action="alterar-senha">
    <input type="hidden" name="usuario_id" value="<?php echo $usuario->getUsuarioId() ?>">

    <p class="mensagem-usuario -atencao">
        Alterando a senha de <b><?php echo $usuario->getNome() ?></b>...<br>
        Caso não seja você, saia dessa página IMEDIATAMENTE!
    </p>

    <p class="form-paragr">
        <label for="senha-atual" class="form-rotulo form-controle-senha">Senha atual:</label>
        <input type="password" name="senha_atual" id="senha-atual" class="form-controle" required>
    </p>

    <p class="form-paragr">
        <label for="senha-nova" class="form-rotulo form-controle-senha-nova">Senha nova:</label>
        <input type="password" name="senha_nova" id="senha-nova" class="form-controle" required>
    </p>

    <p class="form-paragr">
        <label for="senha-confirm" class="form-rotulo form-controle-senha-confirm">Confirmar a senha:</label>
        <input type="password" name="senha_confirm" id="senha-confirm" class="form-controle" required>
    </p>

    <p class="form-botoes">
        <button type="submit" class="botao-alterar-senha">Alterar senha</button>
    </p>
</form>
[/CORPO]

[SCRIPTS]
<script>
    $('#form-alterar-senha').formAjax({
        func_depois: function(retorno) {
            alert(retorno.mensagem);

            if (retorno.retorno === 'sucesso') {
                window.location = '/painel-dlx/usuarios'
            }
        }
    });
</script>
[/SCRIPTS]