<?php
/**
 * MIT License
 *
 * Copyright (c) 2018 PHP DLX
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NON INFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

use DLX\Core\Configure;
use PainelDLX\Domain\Usuarios\Entities\Usuario;
use SechianeX\Factories\SessionFactory;
use Vilex\VileX;

/**
 * @var VileX $this
 */

// TODO: pegar a sessão por atributo
$session = SessionFactory::createPHPSession();

/** @var Usuario|null $usuario */
$usuario = $session->get('usuario-logado');
?>

<html lang="pt">
<head>
    <base href="<?php Configure::get('app', 'base-html') ?>"/>
    <meta name="Content-type" content="text-html">
    <title><?php echo Configure::get('app', 'nome-amigavel') ?></title>

    [ARQUIVOS-CSS/]
    [HTML-HEAD/]
</head>

<body>

<nav class="dlx-menu">
    <?php if ($session->get('logado')) : ?>
    <a href="javascript:" class="link-mostrar-menu" onclick="mostrarOuOcultarMenu()" title="CTRL + ALT + M para abrir o menu">
        Mostrar Menu
    </a>

    <div class="menu-principal">
        <div class="menu-filtro">
            <label>
                <input type="search" id="filtrar-menu" class="form-controle">
            </label>
        </div>

        <a href="javascript:" class="link-fechar-menu" onclick="ocultarMenu()" title="Fechar menu">X</a>

        <div class="menu-item">
            <span class="menu-link">Reservas</span>

            <ul class="sub-menu">
                <li class="sub-menu-item">
                    <a href="#" class="sub-menu-link">
                        Disponibilidade
                    </a>
                </li>

                <li class="sub-menu-item">
                    <a href="#" class="sub-menu-link">
                        Reservas
                    </a>
                </li>

                <li class="sub-menu-item">
                    <a href="#" class="sub-menu-link">
                        Quartos
                    </a>
                </li>
            </ul>
        </div>

        <div class="menu-item">
            <span class="menu-link">Website</span>

            <ul class="sub-menu">
                <li class="sub-menu-item">
                    <a href="#" class="sub-menu-link">
                        Contatos recebidos
                    </a>
                </li>

                <li class="sub-menu-item">
                    <a href="#" class="sub-menu-link">
                        Redes Sociais
                    </a>
                </li>
            </ul>
        </div>

        <div class="menu-item">
            <span class="menu-link">Admin</span>

            <ul class="sub-menu">
                <li class="sub-menu-item">
                    <a href="/painel-dlx/usuarios" class="sub-menu-link">
                        Usuários
                    </a>
                </li>

                <li class="sub-menu-item">
                    <a href="/painel-dlx/grupos-de-usuarios" class="sub-menu-link">
                        Grupos de Usuários
                    </a>
                </li>

                <li class="sub-menu-item">
                    <a href="/painel-dlx/permissoes" class="sub-menu-link">
                        Permissões
                    </a>
                </li>

                <li class="sub-menu-item">
                    <a href="/painel-dlx/config-smtp" class="sub-menu-link">
                        Configurações SMTP
                    </a>
                </li>
            </ul>
        </div>

        <?php if ($usuario instanceof Usuario) : ?>
            <div class="menu-item">
                <span class="menu-link">Minha Conta</span>

                <ul class="sub-menu">
                    <li class="sub-menu-item">
                        <a href="/painel-dlx/minha-conta" class="sub-menu-link">
                            Meus dados
                        </a>
                    </li>

                    <li class="sub-menu-item">
                        <a href="/painel-dlx/alterar-minha-senha" class="sub-menu-link">
                            Alterar minha senha
                        </a>
                    </li>

                    <!-- li class="sub-menu-item">
                        <a href="#" class="sub-menu-link">
                            Configurações
                        </a>
                    </li -->

                    <li class="sub-menu-item">
                        <a href="javascript:" class="sub-menu-link" onclick="encerrarSessao()">
                            Encerrar sessão
                        </a>
                    </li>
                </ul>
            </div>
        <?php endif ?>
    </div>
    <?php endif ?>
</nav>

<div class="wrapper">
    <header class="dlx-topo">
        [TOPO/]
    </header>

    <div class="dlx-conteudo">
        [MENSAGEM-USUARIO/]
        [CORPO/]
    </div>

    <footer class="dlx-rodape">
        [RODAPE/]
    </footer>
</div>

<script src="/vendor/components/jquery/jquery.min.js"></script>
[ARQUIVOS-JAVASCRIPT/]
[SCRIPTS/]
</body>
</html>
