<?php
/**
 * aplicativo
 * @version: versão
 * @author: Diego Lepera
 *
 * Created by Diego Lepera on 2017-07-28. Please report any bug at
 * https://github.com/dlepera88-php/framework-dlx/issues
 *
 * The MIT License (MIT)
 * Copyright (c) 2017 Diego Lepera http://diegolepera.xyz/
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is furnished
 * to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

use DLX\Ajudantes\HTMLForm;
use DLX\Ajudantes\Strings;
use DLX\Ajudantes\Visao;

if(!isset($params)) {
    $params = $this->obterParams();
} // Fim if

$modulo = $params['modelo'];
?>

[DLX-CONTEUDO]
<form id="form-<?php echo $params['html:form-id'] ?>" method="post" action="<?php echo $params['html:form-acao'] ?>" data-url-lista="<?php echo $params['conf:form-url-lista'] ?>" data-url-novo="<?php echo $params['conf:form-url-novo'] ?>" data-url-editar="<?php echo $params['conf:form-url-editar'] ?>">
    <?php echo HTMLForm::array2Input($params['lista:pk-tabela']) ?>

    <fieldset class="form-grupo">
        <legend class="form-legenda"><?php echo $this->traduzir('Geral', 'painel-dlx') ?></legend>

        <p class="form-paragr">
            <?php echo HTMLForm::campoGeral('texto', 'nome', 'nome', $modulo->getNome(), $this->traduzir('Nome', 'painel-dlx'), null, [
                'maxlength' => 100,
                'required'  => 'required'
            ]) ?>
        </p>

        <p class="form-paragr">
            <?php echo HTMLForm::caixaTexto('descr', 'descr', $modulo->getDescr(), $this->traduzir('Descrição', 'painel-dlx')) ?>
        </p>
    </fieldset>

    <fieldset class="form-grupo">
        <legend class="form-legenda"><?php echo $this->traduzir('Menu', 'painel-dlx') ?></legend>

        <p class="form-paragr">
            <?php echo HTMLForm::chkSimNao('exibir_menu', 'exibir-menu', $modulo->isExibirMenu(), $this->traduzir('Exibir no menu?', 'painel-dlx')) ?>
        </p>

        <p class="form-paragr">
            <?php echo HTMLForm::campoGeral('texto', 'link', 'link', $modulo->getLink(), $this->traduzir('Link', 'painel-dlx'), null, [
                'maxlength' => 200
            ]) ?>
        </p>

        <p class="form-paragr">
            <?php echo HTMLForm::campoGeral('numero', 'ordem', 'ordem', $modulo->getOrdem(), $this->traduzir('Ordem', 'painel-dlx'), $this->traduzir('Ordem de exibição no menu.', 'painel-dlx'), [
                'min'       => '-99',
                'max'       => 99,
                'required'  => 'required'
            ]) ?>
        </p>
    </fieldset>

    <fieldset class="form-grupo">
        <legend class="form-legenda"><?php echo $this->traduzir('Configurações', 'painel-dlx') ?></legend>

        <?php if (count($params['lista:modulos-principais']) > 0) : ?>
            <p class="form-paragr">
                <?php echo HTMLForm::comboSelect('pai', 'pai', $modulo->getPai(), $this->traduzir('Módulo principal', 'painel-dlx'), null, [],
                    array_merge(HTMLForm::csAdicionarOpcao('', $this->traduzir('Este é um módulo principal', 'painel-dlx')), $params['lista:modulos-principais'])
                ) ?>
            </p>
        <?php endif ?>

        <p class="form-paragr">
            <?php echo HTMLForm::campoGeral('texto', 'aplicativo', 'aplicativo', $modulo->getAplicativo(), $this->traduzir('Aplicativo', 'painel-dlx'), $this->traduzir('Nome do aplicativo do qual esse módulo faz parte.', 'painel-dlx'), [
                'maxlength' => 50,
                'required'  => 'required'
            ]) ?>
        </p>

        <p class="form-paragr">
            <?php echo HTMLForm::chkSimNao('publicar', 'publicar', $modulo->isPublicar(), $this->traduzir('Ativar?', 'painel-dlx')) ?>
        </p>
    </fieldset>

    <div class="form-botoes">
        <?php echo HTMLForm::botao('salvar', $this->traduzir('Salvar', 'painel-dlx')),
            HTMLForm::botao('cancelar', $this->traduzir('Cancelar', 'painel-dlx')) ?>
    </div>
</form>

<?php if ($params['conf:modulo-principal?']) : ?>
    <div id="lista-submodulos">
        <?php echo Visao::acoplarHTML($params['html:lista-submodulos'], $this) ?>
    </div>
<?php endif;

if ($params['conf:submodulo?']) : ?>
    <div id="lista-submodulos">
        <?php echo Visao::acoplarHTML($params['html:lista-acoes'], $this) ?>
    </div>
<?php endif ?>
[/DLX-CONTEUDO]

[DLX-SCRIPTS]
<script>
    //<![CDATA[
    $('#sel-pai').on('change.__script', function () {
        $.post('desenvolvedor/modulos/herdar-aplicativo', { 'modulo-principal': this.value }, function (aplicativo) {
            $('#txt-aplicativo').val(aplicativo)
                .prop('readonly', typeof aplicativo !== 'undefined' && aplicativo !== '');
        });
    });
    //]]>
</script>
[/DLX-SCRIPTS]
