<?php
/**
 * painel-dlx
 * @version: v1.17.08
 * @author: Diego Lepera
 *
 * Created by Diego Lepera on 2017-07-28. Please report any bug at
 * https://github.com/dlepera88-php/framework-dlx/issues
 *
 * The MIT License (MIT)
 * Copyright (c) 2017 Diego Lepera http://diegolepera.xyz/
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is furnished
 * to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

use DLX\Ajudantes\HTMLForm;
use DLX\Ajudantes\Strings;

if(!isset($params)) {
    $params = $this->obterParams();
} // Fim if

$idioma = $params['modelo'];
?>

[DLX-CONTEUDO]
<form id="form-<?php echo $params['html:form-id'] ?>" method="post" action="<?php echo $params['html:form-acao'] ?>" data-url-lista="<?php echo $params['conf:form-url-lista'] ?>" data-url-novo="<?php echo $params['conf:form-url-novo'] ?>" data-url-editar="<?php echo $params['conf:form-url-editar'] ?>">
    <?php echo HTMLForm::array2Input($params['lista:pk-tabela']) ?>

    <fieldset class="form-grupo">
        <legend class="form-legenda"><?php echo $this->traduzir('Geral', 'painel-dlx') ?></legend>

        <?php if ($params['conf:inserindo-registro?']) : ?>
            <p class="form-paragr">
                <?php echo HTMLForm::campoGeral('texto', 'sigla', 'sigla', $idioma->getSigla(), $this->traduzir('Sigla', 'painel-dlx'), $this->traduzir('Sigla do idioma no padrão pt_BR ou br para português do Brasil, por exemplo.', 'dominio'), [
                    'maxlength'     => 5,
                    'placeholder'   => 'pt_BR / br',
                    'pattern'       => EXPREG_IDIOMA,
                    'style'         => 'width:auto',
                    'required'      => 'required'
                ]) ?>
            </p>
        <?php else : ?>
            <p class="form-paragr">
                <span class="form-rotulo"><?php echo $this->traduzir('Sigla', 'painel-dlx') ?>:</span>
                <?php echo $idioma->getSigla() ?>
            </p>
        <?php endif ?>

        <p class="form-paragr">
            <?php echo HTMLForm::campoGeral('texto', 'nome', 'nome', $idioma->getNome(), $this->traduzir('Nome', 'painel-dlx'), null, [
                'maxlength' => 50,
                'required'  => 'required'
            ]) ?>
        </p>
    </fieldset>

    <fieldset class="form-grupo">
        <legend class="form-legenda"><?php echo $this->traduzir('Configurações', 'painel-dlx'); ?></legend>

        <p class="form-paragr">
            <?php echo HTMLForm::chkSimNao('padrao', 'padrao', $idioma->isPadrao(), $this->traduzir('Padrão?', 'painel-dlx'), $this->traduzir('Define esse grupo como padrão para inclusão de novos usuários.', 'painel-dlx')) ?>
        </p>

        <p class="form-paragr">
            <?php echo HTMLForm::chkSimNao('publicar', 'publicar', $idioma->isPublicar(), $this->traduzir('Ativar?', 'painel-dlx')) ?>
        </p>
    </fieldset>

    <div class="form-botoes">
        <?php echo HTMLForm::botao('salvar', $this->traduzir('Salvar', 'painel-dlx')),
            HTMLForm::botao('cancelar', $this->traduzir('Cancelar', 'painel-dlx')) ?>
    </div>
</form>
[/DLX-CONTEUDO]
