<?php
/**
 * aplicativo
 * @version: versão
 * @author: Diego Lepera
 *
 * Created by Diego Lepera on 2017-07-28. Please report any bug at
 * https://github.com/dlepera88-php/framework-dlx/issues
 *
 * The MIT License (MIT)
 * Copyright (c) 2017 Diego Lepera http://diegolepera.xyz/
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is furnished
 * to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

use DLX\Ajudantes\HTMLForm;
use DLX\Ajudantes\Strings;

if(!isset($params)) {
    $params = $this->obterParams();
} // Fim if

$servidor_dominio = $params['modelo'];
?>

[DLX-CONTEUDO]
<form id="form-<?php echo $params['html:form-id'] ?>" method="post" action="<?php echo $params['html:form-acao'] ?>" data-url-lista="<?php echo $params['conf:form-url-lista'] ?>" data-url-novo="<?php echo $params['conf:form-url-novo'] ?>" data-url-editar="<?php echo $params['conf:form-url-editar'] ?>">
    <?php echo HTMLForm::array2Input($params['lista:pk-tabela']) ?>

    <p class="form-paragr">
        <?php echo HTMLForm::campoGeral('texto', 'dominio', 'dominio', $servidor_dominio->getDominio(), $this->traduzir('Domínio', 'painel-dlx'), null, [
            'placeholder' => 'dominio.local',
            'maxlength'   => 30,
            'required'    => 'required'
        ]); ?>
    </p>

    <p class="form-paragr">
        <?php echo HTMLForm::campoGeral('texto', 'host', 'host', $servidor_dominio->getHost(), $this->traduzir('Host', 'painel-dlx'), $this->traduzir('IP ou hostname do servidor.', 'painel-dlx'), [
            'placeholder' => 'hostname.com / 192.168.0.100',
            'maxlength'   => 100,
            'required'    => 'required'
        ]); ?>
    </p>

    <p class="form-paragr">
        <?php echo HTMLForm::chkSimNao('ativo', 'ativo', $servidor_dominio->isAtivo(), $this->traduzir('Ativar?', 'painel-dlx'), $this->traduzir('Servidores inativos não poderão fazer login no sistema.', 'painel-dlx')); ?>
    </p>

    <div class="form-botoes">
        <?php echo HTMLForm::botao('salvar', $this->traduzir('Salvar', 'painel-dlx')),
            HTMLForm::botao('cancelar', $this->traduzir('Cancelar', 'painel-dlx')); ?>
    </div>
</form>
[/DLX-CONTEUDO]
