<?php
/**
 * aplicativo
 * @version: versão
 * @author: Diego Lepera
 *
 * Created by Diego Lepera on 2017-07-28. Please report any bug at
 * https://github.com/dlepera88-php/framework-dlx/issues
 *
 * The MIT License (MIT)
 * Copyright (c) 2017 Diego Lepera http://diegolepera.xyz/
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is furnished
 * to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

use DLX\Ajudantes\HTMLForm;
use DLX\Ajudantes\Strings;

if(!isset($params)) {
    $params = $this->obterParams();
} // Fim if

$formato_data = $params['modelo'];
?>

[DLX-CONTEUDO]
<form id="form-<?php echo $params['html:form-id']; ?>" method="post" action="<?php echo $params['html:form-acao']; ?>" data-url-lista="<?php echo $params['conf:form-url-lista'] ?>" data-url-novo="<?php echo $params['conf:form-url-novo'] ?>" data-url-editar="<?php echo $params['conf:form-url-editar'] ?>">
    <?php echo HTMLForm::array2Input($params['lista:pk-tabela']) ?>

    <fieldset class="form-grupo">
        <legend class="form-legenda"><?php echo $this->traduzir('Geral', 'painel-dlx'); ?></legend>

        <p class="form-paragr">
            <?php echo HTMLForm::campoGeral('texto', 'descr', 'descr', $formato_data->getDescr(), $this->traduzir('Descrição', 'painel-dlx'), null, [
                'maxlength' => 50,
                'required'  => 'required'
            ]); ?>
        </p>
    </fieldset>

    <fieldset class="form-grupo">
        <legend class="form-legenda"><?php echo $this->traduzir('Configurações', 'painel-dlx'); ?></legend>

        <p class="form-paragr">
            <?php echo HTMLForm::campoGeral('texto', 'completo', 'completo', $formato_data->getCompleto(), $this->traduzir('Formato de data e hora', 'painel-dlx'), $this->traduzir('Formato para exibição da data completa (data e hora).', 'painel-dlx'), [
                'maxlength' => 20,
                'required'  => 'required'
            ]); ?>
        </p>

        <p class="form-paragr">
            <?php echo HTMLForm::campoGeral('texto', 'data', 'data', $formato_data->getData(), $this->traduzir('Formato da data', 'painel-dlx'), $this->traduzir('Formato para exibição apenas da data.', 'painel-dlx'), [
                'maxlength' => 10,
                'required'  => 'required'
            ]); ?>
        </p>

        <p class="form-paragr">
            <?php echo HTMLForm::campoGeral('texto', 'hora', 'hora', $formato_data->getHora(), $this->traduzir('Formato da hora', 'painel-dlx'), $this->traduzir('Formato para exibição apenas da hora.', 'painel-dlx'), [
                'maxlength' => 10,
                'required'  => 'required'
            ]); ?>
        </p>

        <p class="form-paragr">
            <?php echo HTMLForm::chkSimNao('padrao', 'padrao', $formato_data->isPadrao(), $this->traduzir('Padrão?', 'painel-dlx'), $this->traduzir('Define esse formato de data como padrão para inclusão de novos usuários.', 'painel-dlx')); ?>
        </p>

        <p class="form-paragr">
            <?php echo HTMLForm::chkSimNao('publicar', 'publicar', $formato_data->isPublicar(), $this->traduzir('Ativar?', 'painel-dlx')); ?>
        </p>
    </fieldset>

    <div class="form-botoes">
        <?php echo HTMLForm::botao('salvar', $this->traduzir('Salvar', 'painel-dlx')),
            HTMLForm::botao('cancelar', $this->traduzir('Cancelar', 'painel-dlx')); ?>
    </div>
</form>
[/DLX-CONTEUDO]

[DLX-SCRIPTS]
<script>
    //<![CDATA[
    $('#txt-completo').on('change.__script', function () {
        var valor = $(this).val(),
            $data = $('#txt-data'),
            $hora = $('#txt-hora');

        if (valor.indexOf(' ') > -1) {
            $data.val(valor.substr(0, valor.indexOf(' '))).trigger('change');
            $hora.val(valor.substr(valor.indexOf(' '))).trigger('change');
        } else {
            $data.val(valor).trigger('change');
        } // Fim if ... else
    });

    $('#txt-data, #txt-hora, #txt-completo').on('change.__script', function () {
        var $this = $(this);

        $.get('desenvolvedor/formatos-de-datas/testar-formato?formato-data=' + $this.val(), function (data_formatada) {
            $this.find('+ span.teste-data').remove();
            $(document.createElement('span')).addClass('teste-data').html(data_formatada).insertAfter($this);
        });
    });

    $(window).on('load.__script', function () {
        $('#txt-data, #txt-hora, #txt-completo').trigger('change');
    });
    //]]>
</script>
[/DLX-SCRIPTS]
