<?php
/**
 * MIT License
 *
 * Copyright (c) 2018 PHP DLX
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NON INFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

use PainelDLX\Domain\GruposUsuarios\Entities\GrupoUsuario;
use PainelDLX\Domain\PermissoesUsuario\Entities\PermissaoUsuario;
use Vilex\VileX;

/**
 * @var VileX $this
 */

/** @var GrupoUsuario $grupo_usuario */
$grupo_usuario = $this->getAtributo('grupo-usuario');

/** @var array $lista_permissoes */
$lista_permissoes = $this->getAtributo('lista-permissoes');
?>

[CORPO]
<h1 class="titulo-pagina"><?php echo $this->getAtributo('titulo-pagina') ?></h1>

<form id="form-config-permissoes" method="post" action="/painel-dlx/grupos-de-usuarios/configurar-permissoes" class="form-config-permissoes">
    <input type="hidden" name="grupo_usuario_id" value="<?php echo $grupo_usuario->getGrupoUsuarioId() ?>">

    <fieldset class="form-grupo">
        <legend class="form-titulo">Sistema</legend>

        <table class="lista-registros lista-gerenciar-permissoes" id="lista-permissoes-sistema">
            <tbody>
            <?php
            /** @var PermissaoUsuario $permissao */
            foreach ($lista_permissoes as $permissao) :
                if (!$grupo_usuario->hasPermissao($permissao)) : ?>
                <tr data-permissao="<?php echo $permissao->getPermissaoUsuarioId() ?>" onclick="adicionarPermissao(this)">
                    <td>
                        <input type="checkbox" name="permissao_usuario_ids[]" value="<?php echo $permissao->getPermissaoUsuarioId() ?>">
                        <?php echo $permissao->getDescricao() ?>
                    </td>
                </tr>
                <?php endif;
            endforeach; ?>
            </tbody>
        </table>
    </fieldset>

    <fieldset class="form-grupo">
        <legend class="form-titulo"><?php echo $grupo_usuario->getNome() ?></legend>

        <table class="lista-registros lista-gerenciar-permissoes" id="lista-permissoes-grupo">
            <tbody>
            <?php foreach ($grupo_usuario->getPermissoes() as $permissao) : ?>
                <tr onclick="retirarPermissao(this)">
                    <td>
                        <input type="checkbox" name="permissao_usuario_ids[]" value="<?php echo $permissao->getPermissaoUsuarioId() ?>" checked>
                        <?php echo $permissao->getDescricao() ?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </fieldset>

    <p class="form-botoes">
        <button type="submit" class="botao-salvar" data-ajax-msg="Configurando permissões do grupo.<br>Por favor aguarde...">
            Salvar
        </button>
    </p>
</form>
[/CORPO]

[SCRIPTS]
<script>
    $('#form-config-permissoes').formAjax();
</script>
[/SCRIPTS]