<?php
/**
 * MIT License
 *
 * Copyright (c) 2018 PHP DLX
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NON INFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

use PainelDLX\Domain\GruposUsuarios\Entities\GrupoUsuario;
use Vilex\VileX;

/**
 * @var VileX $this
 */

$lista_grupos_usuarios = $this->getAtributo('lista_grupos_usuarios');
$filtro = $this->getAtributo('filtro');
?>

[CORPO]
<h1 class="titulo-pagina"><?php echo $this->getAtributo('titulo-pagina') ?></h1>

<nav class="menu-opcoes">
    <form id="filtro-registros" class="filtro-registros">
        <div class="multi-select">
            <span class="multi-select-item">Procurar em...</span>

            <div class="multi-select-itens">
                <label class="multi-select-item">
                    <input type="checkbox" name="campos[]" value="alias"<?php echo empty($filtro['campos']) || in_array('alias', $filtro['campos']) ? ' checked' : '' ?>>
                    Alias
                </label>

                <label class="multi-select-item">
                    <input type="checkbox" name="campos[]" value="nome"<?php echo empty($filtro['campos']) || in_array('nome', $filtro['campos']) ? ' checked' : '' ?>>
                    Grupo
                </label>
            </div>
        </div>

        <input type="search" name="busca" value="<?php echo $filtro['busca'] ?>" placeholder="Encontrar grupos de usuários" class="form-controle">
    </form>

    <button type="submit" form="filtro-registros" class="botao-buscar">Buscar</button>
    <a href="/painel-dlx/grupos-de-usuarios/novo" class="link-inserir">Adicionar grupo de usuário</a>
</nav>

<table id="lista-grupos-usuarios" class="lista-registros">
    <thead>
    <tr>
        <th id="grupo-usuario-id">ID</th>
        <th id="alias">Alias</th>
        <th id="grupo">Grupo</th>
        <th id="opcoes">Opções</th>
    </tr>
    </thead>

    <tbody>
    <?php if (!count($lista_grupos_usuarios)) : ?>
    <tr>
        <td colspan="4" class="sem-registros">Nenhum grupo de usuário encontrado.</td>
    </tr>
    <?php endif;

    /** @var GrupoUsuario $grupo_usuario */
    foreach ($lista_grupos_usuarios as $grupo_usuario) : ?>
        <tr>
            <td headers="grupo-usuario-id"><?php echo $grupo_usuario->getGrupoUsuarioId() ?></td>
            <td headers="alias"><?php echo $grupo_usuario->getAlias() ?></td>
            <td headers="grupo">
                <?php echo $grupo_usuario->getNome() ?><br>
                <span class="lista-registros-comentario">
                <?php
                    $qtde_usuarios = $grupo_usuario->getUsuarios()->count();

                    switch ($qtde_usuarios) {
                        case 0: echo 'Nenhum usuário nesse grupo.'; break;
                        case 1: echo 'Apenas 1 usuário nesse grupo.'; break;
                        default: printf('%d usuários nesse grupo.', $qtde_usuarios); break;
                    }
                ?>
                </span>
            </td>
            <td headers="opcoes">
                <a href="/painel-dlx/grupos-de-usuarios/detalhe?grupo_usuario_id=<?php echo $grupo_usuario->getGrupoUsuarioId() ?>" class="link-detalhe">
                    Detalhe
                </a>

                <a href="/painel-dlx/grupos-de-usuarios/editar?grupo_usuario_id=<?php echo $grupo_usuario->getGrupoUsuarioId() ?>" class="link-editar">
                    Editar
                </a>

                <a href="javascript:" class="link-excluir" onclick="excluirGrupoUsuario(<?php echo $grupo_usuario->getGrupoUsuarioId() ?>)" data-ajax-msg="Excluindo grupo de usuário.<br>Por favor aguarde...">
                    Excluir
                </a>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
[/CORPO]