<?php
/**
 * MIT License
 *
 * Copyright (c) 2018 PHP DLX
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NON INFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

use PainelDLX\Domain\GruposUsuarios\Entities\GrupoUsuario;
use PainelDLX\Domain\PermissoesUsuario\Entities\PermissaoUsuario;
use Vilex\VileX;

/**
 * @var VileX $this
 */

/** @var GrupoUsuario $grupo_usuario */
$grupo_usuario = $this->getAtributo('grupo_usuario');
?>

[CORPO]
<h1 class="titulo-pagina"><?php echo $this->getAtributo('titulo-pagina') ?></h1>

<form id="form-grupo-usuario" method="post" action="/painel-dlx/grupos-de-usuarios/salvar">
    <input type="hidden" name="grupo_usuario_id" value="<?php echo $grupo_usuario->getGrupoUsuarioId() ?>">

    <fieldset class="form-grupo">
        <legend class="form-titulo">Geral</legend>

        <p class="form-paragr">
            <span class="Alias">Alias (apelido):</span>
            <?php echo $grupo_usuario->getAlias() ?>
        </p>

        <p class="form-paragr">
            <label for="txt-nome" class="form-rotulo form-controle-grupo">Nome:</label>
            <input type="text" name="nome" id="txt-nome" value="<?php echo $grupo_usuario->getNome() ?>" class="form-controle form-controle-texto" required>
        </p>
    </fieldset>

    <fieldset class="form-grupo">
        <legend class="form-titulo">Permissões</legend>

        <a href="javascript:" onclick="popupGerenciarConfiguracoes(<?php echo $grupo_usuario->getGrupoUsuarioId() ?>)" class="botao-gerenciar-permissoes">
            Gerenciar permissões
        </a>

        <ul class="lista-permissoes">
            <?php
            /** @var PermissaoUsuario $permissao */
            foreach ($grupo_usuario->getPermissoes() as $permissao) : ?>
                <li class="permissao">
                    <?php echo $permissao->getDescricao() ?><br>
                    <?php echo $permissao->getAlias() ?>
                </li>
            <?php endforeach ?>
        </ul>
    </fieldset>

    <p class="form-botoes">
        <button type="submit" class="botao-salvar">Salvar</button>
    </p>
</form>
[/CORPO]

[SCRIPTS]
<script>
    $('#form-grupo-usuario').formAjax({
        func_depois: function(retorno) {
            alert(retorno.mensagem);

            if (retorno.retorno === 'sucesso') {
                window.location.reload();
            }
        }
    });
</script>
[/SCRIPTS]