<?php
/**
 * MIT License
 *
 * Copyright (c) 2018 PHP DLX
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NON INFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

use PainelDLX\Domain\CadastroUsuarios\Entities\GrupoUsuario;
use Vilex\VileX;

/**
 * @var VileX $this
 */

$lista_grupos = $this->getAtributo('lista_grupos')
?>

[CORPO]
<h1 class="titulo-pagina"><?php echo $this->getAtributo('titulo-pagina') ?></h1>

<form id="form-usuario" method="post" action="/painel-dlx/usuarios/cadastrar-novo-usuario" onsubmit="return cadastrarNovoUsuario(this)">
    <fieldset class="form-grupo">
        <legend class="form-titulo">Dados Pessoais</legend>

        <p class="form-paragr">
            <label for="txt-nome" class="form-rotulo">Nome:</label>
            <input type="text" name="nome" id="txt-nome" class="form-controle form-controle-texto" required>
        </p>

        <p class="form-paragr">
            <label for="txt-email" class="form-rotulo">Email:</label>
            <input type="email" name="email" id="txt-email" placeholder="seunome@gmail.com" class="form-controle form-controle-email" required>
        </p>
    </fieldset>


    <fieldset class="form-grupo">
        <legend class="form-titulo">Acesso ao Sistema</legend>

        <p class="form-paragr">
            <label for="txt-senha" class="form-rotulo">Senha:</label>
            <input type="password" name="senha" id="txt-senha" class="form-controle form-controle-senha" required>
        </p>

        <p class="form-paragr">
            <label for="txt-senha-confirm" class="form-rotulo">Confirme a senha:</label>
            <input type="password" name="senha_confirm" id="txt-senha-confirm" class="form-controle form-controle-senha" required>
        </p>
    </fieldset>

    <fieldset class="form-grupo">
        <legend class="form-titulo">Grupos</legend>

        <?php if ($lista_grupos) : ?>
            <div class="lista-grupos">
                <?php
                /** @var GrupoUsuario $grupo_usuario */
                foreach($lista_grupos as $grupo_usuario) : ?>
                    <p class="form-paragr">
                        <input type="checkbox" name="grupos[]" id="chk-grupo-usuario-<?php echo $grupo_usuario->getGrupoUsuarioId() ?>" value="<?php echo $grupo_usuario->getGrupoUsuarioId() ?>" class="form-controle form-controle-checkbox">
                        <label for="chk-grupo-usuario-<?php echo $grupo_usuario->getGrupoUsuarioId() ?>"><?php echo $grupo_usuario->getNome() ?></label>
                    </p>
                <?php endforeach ?>
            </div>
        <?php else : ?>
            <p class="sem-registros">Nenhum grupo de usuário encontrado.</p>
        <?php endif ?>
    </fieldset>

    <p class="form-botoes">
        <button type="submit" class="btn btn-salvar">Salvar</button>
        <button type="reset" class="btn btn-cancelar">Cancelar</button>
    </p>
</form>
[/CORPO]

[SCRIPTS]
<script>
    function cadastrarNovoUsuario(form) {
        var $form = $(form);

        $.ajax({
            url: $form.attr('action'),
            type: $form.attr('method'),
            data: $form.serialize(),
            dataType: 'json',
            success: function(retorno) {
                alert(retorno.mensagem);

                if (retorno.retorno === 'sucesso') {
                    window.location = '/painel-dlx/usuarios'
                }
            }
        });

        return false;
    }
</script>
[/SCRIPTS]