<?php
/**
 * MIT License
 *
 * Copyright (c) 2018 PHP DLX
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NON INFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

use PainelDLX\Domain\CadastroUsuarios\Entities\Usuario;
use Vilex\VileX;

/**
 * @var VileX $this
 */

$lista_usuarios = $this->getAtributo('lista_usuarios');
?>
[CORPO]
<h1 class="titulo-pagina"><?php echo $this->getAtributo('titulo-pagina') ?></h1>

<nav class="menu-opcoes">
    <a href="/painel-dlx/usuarios/novo">Adicionar usuário</a>
</nav>

<table id="lista-usuarios" class="lista-registros">
    <thead>
    <tr>
        <th id="usuario-id">ID</th>
        <th id="nome">Nome</th>
        <th id="opcoes">Opções</th>
    </tr>
    </thead>

    <tbody>
    <?php if (!count($lista_usuarios)) : ?>
    <tr>
        <td colspan="3">Nenhum usuário encontrado.</td>
    </tr>
    <?php endif;

    /** @var Usuario $usuario */
    foreach ($lista_usuarios as $usuario) : ?>
        <tr>
            <td headers="usuario-id"><?php echo $usuario->getUsuarioId() ?></td>
            <td headers="usuario">
                <?php echo $usuario->getNome() ?><br>
                <?php echo $usuario->getEmail() ?>
            </td>
            <td headers="opcoes">
                <a href="/painel-dlx/usuarios/detalhe?usuario_id=<?php echo $usuario->getUsuarioId() ?>" class="link-detalhe" title="Informações desse usuário">
                    Detalhe
                </a>

                <a href="/painel-dlx/usuarios/editar?usuario_id=<?php echo $usuario->getUsuarioId() ?>" class="link-editar" title="Editar esse usuário">
                    Editar
                </a>

                <a href="javascript:" class="link-excluir" onclick="excluirUsuario(<?php echo $usuario->getUsuarioId() ?>)" title="Excluir esse usuário">
                    Excluir
                </a>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
[/CORPO]

[SCRIPTS]
<script>
    function excluirUsuario(usuario_id) {
        if (confirm('Deseja realmente excluir esse usuário?')) {
            $.ajax({
                url: '/painel-dlx/usuarios/excluir-usuario',
                type: 'post', //delete
                data: 'usuario_id=' + usuario_id,
                dataType: 'json',
                success: function (retorno) {
                    alert(retorno.mensagem);
                    window.location.reload();
                }
            })
        }

        return false;
    }
</script>
[/SCRIPTS]