<?php
/**
 * MIT License
 *
 * Copyright (c) 2018 PHP DLX
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NON INFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

use DLX\Core\Configure;
use Vilex\VileX;

/**
 * @var VileX $this
 */
?>

<html>
<head>
    <base href="<?php Configure::get('app', 'base-html') ?>"/>
    <meta name="Content-type" content="text-html">
    <title><?php echo Configure::get('app', 'nome-amigavel') ?></title>

    [ARQUIVOS-CSS/]
    [HTML-HEAD/]
</head>

<body>
<nav class="dlx-menu">
    <label>
        <input type="search" id="filtrar-menu" class="form-controle menu-filtro">
    </label>

    <a href="javascript:" class="link-mostrar-menu" onclick="mostrarMenu()" title="Abrir menu">
        Mostrar Menu
    </a>

    <ul class="menu-principal">
        <a href="javascript:" class="link-fechar-menu" onclick="mostrarMenu()" title="Fechar menu">X</a>

        <li class="menu-item">
            <span class="menu-link">Admin</span>

            <ul class="sub-menu">
                <li class="sub-menu-item">
                    <a href="/painel-dlx/usuarios" class="sub-menu-link">
                        Usuários
                    </a>
                </li>

                <li class="sub-menu-item">
                    <a href="/painel-dlx/grupos-de-usuarios" class="sub-menu-link">
                        Grupos de Usuários
                    </a>
                </li>
            </ul>
        </li>
    </ul>
</nav>

<div class="wrapper">
    <header class="dlx-topo">
        [TOPO/]
    </header>

    <div class="dlx-conteudo">
        [CORPO/]
    </div>

    <footer class="dlx-rodape">
        [RODAPE/]
    </footer>
</div>

<!-- TODO: CRIAR OPÇÃO PARA O VILEX ADICIONAR OS JS COMO ERA FEITO NO DLX ORIGINAL -->
<script src="/vendor/components/jquery/jquery.min.js"></script>
[ARQUIVOS-JAVASCRIPT/]
[SCRIPTS/]
</body>
</html>
