<?php
/**
 * MIT License
 *
 * Copyright (c) 2018 PHP DLX
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NON INFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

use Vilex\VileX;

/**
 * @var VileX $this
 */
?>

[CORPO]
<h1 class="titulo-pagina"><?php echo $this->getAtributo('titulo-pagina') ?></h1>

<form id="form-config-smtp" method="post" action="">
    <fieldset class="form-grupo">
        <legend class="form-titulo">Geral</legend>

        <p class="form-paragr">
            <label for="txt-nome" class="form-rotulo form-controle-alias">Nome</label>
            <input type="text" name="nome" id="txt-nome" class="form-controle" maxlength="30" required>
        </p>

        <p class="form-paragr">
            <label for="txt-servidor" class="form-rotulo form-controle-servidor">Servidor</label>
            <input type="text" name="servidor" id="txt-servidor" maxlength="30" class="form-controle" required> :
            <input type="number" name="porta" value="25" min="25" max="65535" size="5" class="form-controle" required>
        </p>
    </fieldset>

    <fieldset class="form-grupo">
        <legend class="form-titulo">Autenticação</legend>

        <p class="form-paragr">
            <span class="form-rotulo">Requer autenticação?</span>
            <input type="checkbox" name="requer_autent" value="1">
        </p>

        <div class="config-autenticacao-servidor">
            <p class="form-paragr">
                <label for="txt-conta" class="form-rotulo form-controle-usuario">Conta</label>
                <input type="text" name="conta" id="txt-conta" maxlength="100" class="form-controle">
            </p>

            <p class="form-paragr">
                <label for="txt-senha" class="form-rotulo form-controle-senha">Senha</label>
                <input type="text" name="senha" id="txt-senha" maxlength="20" class="form-controle">
            </p>

            <p class="form-paragr">
                <label for="sel-cripto" class="form-rotulo form-controle-cripto">Tipo de criptografia</label>
                <select name="cripto" id="sel-cripto" class="form-controle">
                    <option value="">Nenhuma</option>
                    <option value="tls">TLS</option>
                    <option value="ssl">SSL</option>
                </select>
            </p>
        </div>
    </fieldset>

    <fieldset class="form-grupo">
        <legend class="form-titulo">Configurações</legend>

        <p class="form-paragr">
            <label for="txt-de-nome" class="form-rotulo form-controle-descricao">De (nome)</label>
            <input type="text" name="de_nome" id="txt-de-nome" maxlength="50" class="form-controle">
        </p>

        <p class="form-paragr">
            <label for="txt-responder-para" class="form-rotulo form-controle-email">Responder para</label>
            <input type="email" name="responder_para" id="txt-responder-para" maxlength="100" class="form-controle">
        </p>

        <p class="form-paragr">
            <span class="form-rotulo">Enviar corpo em formato HTML?</span>
            <input type="checkbox" name="corpo_html" value="1">
        </p>
    </fieldset>

    <p class="form-botoes">
        <button type="submit" class="botao-salvar">Salvar</button>
    </p>
</form>
[/CORPO]

[SCRIPTS]
<script>
    $('#form-config-smtp').formAjax({
        func_depois: function(retorno) {
            alert(retorno.mensagem);

            if (retorno.retorno === 'sucesso') {
                window.location = '/painel-dlx/config-smtp'
            }
        }
    });
</script>
[/SCRIPTS]