<?php
/**
 * MIT License
 *
 * Copyright (c) 2018 PHP DLX
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NON INFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

use PainelDLX\Domain\Emails\Entities\ConfigSmtp;
use Vilex\VileX;

/**
 * @var VileX $this
 */

$lista_config_smtp = $this->getAtributo('lista-config-smtp');
?>

[CORPO]
<h1 class="titulo-pagina"><?php echo $this->getAtributo('titulo-pagina') ?></h1>

<nav class="menu-opcoes">
    <a href="/painel-dlx/config-smtp/nova" class="link-inserir">Adicionar configuração SMTP</a>
</nav>

<table id="lista-config-smtp" class="lista-registros">
    <thead>
    <tr>
        <th id="config-smtp-id">ID</th>
        <th id="nome">Nome</th>
        <th id="servidor">Servidor</th>
        <th id="opcoes">Opções</th>
    </tr>
    </thead>

    <tbody>
    <?php if (!count($lista_config_smtp)) : ?>
    <tr>
        <td colspan="3">Nenhuma configuração SMTP encontrada.</td>
    </tr>
    <?php endif;

    /** @var ConfigSmtp $config_smtp */
    foreach ($lista_config_smtp as $config_smtp) : ?>
        <tr>
            <td headers="config-smtp-id"><?php echo $config_smtp->getConfigSmtpId() ?></td>
            <td headers="nome"><?php echo $config_smtp->getNome() ?></td>
            <td headers="servidor">
                <?php echo "{$config_smtp->getServidor()}:{$config_smtp->getPorta()}" ?>
            </td>
            <td headers="opcoes">
                <a href="/painel-dlx/config-smtp/detalhe?config_smtp_id=<?php echo $config_smtp->getConfigSmtpId() ?>" class="link-detalhe">
                    Detalhe
                </a>

                <a href="/painel-dlx/config-smtp/editar?config_smtp_id=<?php echo $config_smtp->getConfigSmtpId() ?>" class="link-editar">
                    Editar
                </a>

                <a href="javascript:" class="link-excluir" onclick="excluirConfigSmtp(<?php echo $config_smtp->getConfigSmtpId() ?>)">
                    Excluir
                </a>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
[/CORPO]

[SCRIPTS]
<script>
    function excluirConfigSmtp(config_smtp_id) {
        if (confirm('Deseja realmente excluir essa configuração SMTP?')) {
            $.ajax({
                url: '/painel-dlx/config-smtp/excluir-config-smtp',
                type: 'post', //delete
                data: 'config_smtp_id=' + config_smtp_id,
                dataType: 'json',
                success: function (retorno) {
                    alert(retorno.mensagem);
                    window.location.reload();
                },
                error: function (jqXHR, status) {
                    alert('Eita! Ocorreu um erro na sua requisição!\nTipo de erro: ' + status);
                }
            })
        }

        return false;
    }
</script>
[/SCRIPTS]