<?php
/**
 * MIT License
 *
 * Copyright (c) 2018 PHP DLX
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NON INFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

use Vilex\VileX;

/**
 * @var VileX $this
 */
global $configure;
?>

<html>
<head>
    <meta name="Content-type" content="text-html">
    <title><?php echo $configure->get('app')['nome-amigavel'] ?></title>

    [ARQUIVOS-CSS/]
    [HTML-HEAD/]
</head>

<body>
<header class="dlx-topo">
    [TOPO/]
</header>

<div class="dlx-conteudo">
    [CORPO/]
</div>

<footer class="dlx-rodape">
    [RODAPE/]
</footer>

[ARQUIVOS-JAVASCRIPTS/]
[JAVASCRIPTS/]
</body>
</html>
