<?php
/**
 * MIT License
 *
 * Copyright (c) 2018 PHP DLX
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NON INFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

use PainelDLX\Domain\Emails\Entities\ConfigSmtp;
use Vilex\Templates\AbstractTemplate;

/**
 * @var AbstractTemplate $this
 */

/** @var ConfigSmtp $config_smtp */
$config_smtp = $this->getAtributo('config-smtp');
?>

[CORPO]
<h1 class="titulo-pagina">{{ titulo-pagina }}</h1>

<details class="detalhe-registro" open>
    <summary class="detalhe-registro-titulo">Geral</summary>

    <p class="detalhe-registro-paragr">
        <span class="detalhe-registro-rotulo">Nome</span>
        <?php echo $config_smtp->getNome() ?>
    </p>

    <p class="detalhe-registro-paragr">
        <span class="detalhe-registro-rotulo">Servidor</span>
        <?php echo "{$config_smtp->getServidor()}:{$config_smtp->getPorta()}" ?>
    </p>
</details>

<details class="detalhe-registro" open>
    <summary class="detalhe-registro-titulo">Autenticação</summary>

    <p class="detalhe-registro-paragr">
        <span class="detalhe-registro-rotulo">Requer autenticação?</span>
        <?php echo $config_smtp->isRequerAutent() ? 'Sim' : 'Náo' ?>
    </p>

    <?php if ($config_smtp->isRequerAutent()) : ?>
        <p class="detalhe-registro-paragr">
            <span class="detalhe-registro-rotulo">Conta</span>
            <?php echo $config_smtp->getConta() ?>
        </p>

        <p class="detalhe-registro-paragr">
            <span class="detalhe-registro-rotulo">Senha</span>
            <?php echo $config_smtp->getSenha() ?>
        </p>

        <p class="detalhe-registro-paragr">
            <span class="detalhe-registro-rotulo">Tipo de criptografia</span>
            <?php echo $config_smtp->getCripto() ?? 'Nenhum' ?>
        </p>
    <?php endif ?>
</details>

<details class="detalhe-registro" open>
    <summary class="detalhe-registro-titulo">Configurações</summary>

    <p class="detalhe-registro-paragr">
        <span class="detalhe-registro-rotulo">De (nome)</span>
        <?php echo $config_smtp->getDeNome() ?>
    </p>

    <p class="detalhe-registro-paragr">
        <span class="detalhe-registro-rotulo">Responder para</span>
        <?php echo $config_smtp->getResponderPara() ?>
    </p>

    <p class="detalhe-registro-paragr">
        <span class="detalhe-registro-rotulo">Enviar corpo em formato HTML?</span>
        <?php echo $config_smtp->isCorpoHtml() ? 'Sim' : 'Não' ?>
    </p>
</details>

<button type="button" onclick="testarConfigSmtp({config_smtp_id: <?php echo $config_smtp->getId() ?>})" class="botao-testar-email" title="Testar essa configuração SMTP">
    Testar
</button>
[/CORPO]