<?php
/**
 * MIT License
 *
 * Copyright (c) 2018 PHP DLX
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NON INFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

use PainelDLX\Domain\Emails\Entities\ConfigSmtp;
use Vilex\VileX;

/**
 * @var VileX $this
 */

$config_smtp = $this->getAtributo('config-smtp') ?? new ConfigSmtp()
?>

[CORPO]
<h1 class="titulo-pagina"><?php echo $this->getAtributo('titulo-pagina') ?></h1>

<form id="form-config-smtp" method="post" action="<?php echo $config_smtp->getConfigSmtpId() ? '/painel-dlx/config-smtp/atualizar-config-smtp' : '/painel-dlx/config-smtp/salvar-config-smtp' ?>">
    <input type="hidden" name="config_smtp_id" value="<?php echo $config_smtp->getConfigSmtpId() ?>">

    <fieldset class="form-grupo">
        <legend class="form-titulo">Geral</legend>

        <p class="form-paragr">
            <label for="txt-nome" class="form-rotulo form-controle-alias">Nome</label>
            <input type="text" name="nome" id="txt-nome" value="<?php echo $config_smtp->getNome() ?>" class="form-controle" maxlength="30" required>
        </p>

        <p class="form-paragr">
            <label for="txt-servidor" class="form-rotulo form-controle-servidor">Servidor</label>
            <input type="text" name="servidor" id="txt-servidor" value="<?php echo $config_smtp->getServidor() ?>" maxlength="30" class="form-controle" required> :
            <input type="number" name="porta" value="<?php echo $config_smtp->getPorta() ?>" min="25" max="65535" size="5" class="form-controle form-controle-numero" required>
        </p>
    </fieldset>

    <fieldset class="form-grupo">
        <legend class="form-titulo">Autenticação</legend>

        <p class="form-paragr">
            <span class="form-rotulo">Requer autenticação?</span>
            <input type="checkbox" name="requer_autent" id="chk-requer-autent" value="1"<?php echo $config_smtp->isRequerAutent() ? ' CHECKED' : '' ?>>
        </p>

        <div id="config-autenticacao-servidor"<?php echo !$config_smtp->isRequerAutent() ? ' style="display: none;"' : '' ?>>
            <p class="form-paragr">
                <label for="txt-conta" class="form-rotulo form-controle-usuario">Conta</label>
                <input type="text" name="conta" id="txt-conta" value="<?php echo $config_smtp->getConta() ?>" maxlength="100" class="form-controle">
            </p>

            <p class="form-paragr">
                <label for="txt-senha" class="form-rotulo form-controle-senha">Senha</label>
                <input type="text" name="senha" id="txt-senha" value="<?php echo $config_smtp->getSenha() ?>" maxlength="20" class="form-controle">
            </p>

            <p class="form-paragr">
                <label for="sel-cripto" class="form-rotulo form-controle-cripto">Tipo de criptografia</label>
                <select name="cripto" id="sel-cripto" class="form-controle form-controle-select">
                    <option value="">Nenhuma</option>
                    <option value="tls"<?php echo $config_smtp->getCripto() === 'tls' ? ' SELECTED' : '' ?>>
                        TLS
                    </option>
                    <option value="ssl"<?php echo $config_smtp->getCripto() === 'ssl' ? ' SELECTED' : '' ?>>
                        SSL
                    </option>
                </select>
            </p>
        </div>
    </fieldset>

    <fieldset class="form-grupo">
        <legend class="form-titulo">Configurações</legend>

        <p class="form-paragr">
            <label for="txt-de-nome" class="form-rotulo form-controle-descricao">De (nome)</label>
            <input type="text" name="de_nome" id="txt-de-nome" value="<?php echo $config_smtp->getDeNome() ?>" maxlength="50" class="form-controle">
        </p>

        <p class="form-paragr">
            <label for="txt-responder-para" class="form-rotulo form-controle-email">Responder para</label>
            <input type="email" name="responder_para" id="txt-responder-para" value="<?php echo $config_smtp->getResponderPara() ?>" maxlength="100" class="form-controle">
        </p>

        <p class="form-paragr">
            <span class="form-rotulo">Enviar corpo em formato HTML?</span>
            <input type="checkbox" name="corpo_html" value="1"<?php echo $config_smtp->isCorpoHtml() ? ' CHECKED' : '' ?>>
        </p>
    </fieldset>

    <p class="form-botoes">
        <button type="submit" class="botao-salvar" data-ajax-msg="Salvando a configuração SMTP.<br>Por favor aguarde...">Salvar</button>
        <button type="button" id="botao-testar-email" class="botao-testar-email" onclick="testarConfigSmtp(<?php echo $config_smtp->getConfigSmtpId() ?>)" title="Testar a configuração SMTP">
            Testar
        </button>
    </p>
</form>
[/CORPO]

[SCRIPTS]
<script>
    $('#form-config-smtp').formAjax({
        func_depois: function (json, form, xhr) {
            if (json.retorno === 'sucesso') {
                msgUsuario.adicionar(json.mensagem, json.retorno, xhr.id);
                window.location = '/painel-dlx/config-smtp/editar?config_smtp_id=' + json.config_smtp_id;
            }

            msgUsuario.mostrar(json.mensagem, json.retorno, xhr.id);
        }
    });

    $('#chk-requer-autent').on('change', function () {
        $('#config-autenticacao-servidor').css(
            'display',
            $(this).prop('checked') ? 'block' : 'none'
        )
    });
</script>
[/SCRIPTS]