<?php
use DLX\Ajudantes\Sessao;
use DLX\Ajudantes\Visao as AjdVisao;

# Parâmetros passados para a página
$params = $this->obterParams();
?>

<!DOCTYPE html>
<html lang="<?php echo $params['config-aplicativo']['idioma'] ?>">
<head>
    <base href="<?php echo $params['conf:base-html'] ?>"/>
    <title><?php echo "{$params['tag-title']} | {$params['config-aplicativo']['nome']}" ?></title>

    <!-- Meta TAGS -->
    <meta charset="<?php echo $params['config-aplicativo']['encoding'] ?>">

    <!-- Tamanho do dispositivo -->
    <meta name="viewport" content="width=device-width,initial-scale=1.0">

    <!-- Compatibilidade IE -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <!-- Favicon -->
    <link rel="shortcut icon" href="<?php echo "{$params['diretorio-relativo']}{$params['config-aplicativo']['favicon']}" ?>"/>

    <!-- <head> Conteúdo personalizado </head> -->
    [DLX-HEAD/]

    <!-- CSS -->
    [DLX-ARQUIVOS-CSS/]
    [DLX-CSS/]
</head>
<body>

<!-- Verificar JavaScript -->
<noscript class="mostrar-msg -erro"><?php echo $this->traduzir('Seu navegador está configurado para <b>não</b> utilizar <b>JavaScript</b>! O sistema não funcionará corretamente. Por favor, ative o JavaScript do seu navegador e atualize a página.') ?></noscript>

<!-- Verificar versão do IE -->
<p class="mostrar-msg -erro" id="ie-incompativel" style="display: none;"><?php echo $this->traduzir('Essa versão do <b>Internet Explorer</b> é antiga e não é suportada pelo sistema. Por favor, atualize para a versão mais recente do IE ou instale e utilize o <b>Google Chrome</b>.') ?></p>

<div id="dlx-grid">
    <header class="dlx-topo">
        <a href="javascript:" rel="nofollow" id="lk-mostrar-menu" class="mostrar-menu"></a>
        <a href="" class="logo-site"><?php echo $params['config-aplicativo']['nome'] ?></a>

        [DLX-TOPO/]

        <nav class="menu-topo">
            [DLX-MENU-TOPO/]
        </nav>
    </header>

    <nav class="dlx-menu">
        [DLX-MENU/]
    </nav>

    <div class="dlx-conteudo">
        <h1 class="titulo-h1">
            <?php echo $params['html:titulo-pagina'] ?>
            [DLX-MENU-OPCOES/]
        </h1>

        [DLX-MENSAGENS-USUARIO/]
        [DLX-CONTEUDO/]
    </div>

    <footer class="dlx-rodape">
        [DLX-RODAPE/]
    </footer>
</div>

<!-- Carregando -->
<div id="status-ajax" class="status-ajax"></div>

<!-- Javascripts -->
[DLX-ARQUIVOS-JS/]
[DLX-SCRIPTS/]
</body>
</html>
