<?php
/**
 * Created by PhpStorm.
 * User: dlepera
 * Date: 11/02/16
 * Time: 17:53
 */

if (!isset($params)) {
    $params = $this->obterParams();
} // Fim if
?>

[DLX-SCRIPTS]
<script>
    //<![CDATA[
    carregarJS('<?php echo "{$params['diretorio-relativo']}{$params['config-aplicativo']['dir-js']}"; ?>dl-paginacao/dl-paginacao-2.2.plugin-min.js');

    $__paginacao = $('#paginacao').paginacao({
        pgtotal: <?php echo $params['info:qtde-total-paginas']; ?>,
        mostrar: 5,
        tema: '<?php echo $params['config-aplicativo']['plugins-jquery']['paginacao']['tema']; ?>'
    });
    //]]>
</script>
[/DLX-SCRIPTS]
