<?php
/**
 * painel-dlx
 * @version: v1.17.08
 * @author: Diego Lepera
 *
 * Created by Diego Lepera on 2017-07-28. Please report any bug at
 * https://github.com/dlepera88-php/framework-dlx/issues
 *
 * The MIT License (MIT)
 * Copyright (c) 2017 Diego Lepera http://diegolepera.xyz/
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is furnished
 * to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

use \DLX\Ajudantes\HTMLLinks;
use \DLX\Ajudantes\HTMLLista;
use \DLX\Ajudantes\Sessao;
use \DLX\Ajudantes\Vetores;

if (!isset($params)) {
    $params = $this->obterParams();
} // Fim if

$mostrar_id = Sessao::dadoSessao('usuario_pref_exibir_id', FILTER_VALIDATE_BOOLEAN, true);

$opcoes_registro = Vetores::extrairElementos($params, ['html:opcoes-registro', 'html:mais-opcoes-registro'], function ($elemento) {
    return isset($elemento);
});

$opcoes_registro_massa = Vetores::extrairElementos($params, ['html:opcoes-registro-massa', 'html:mais-opcoes-registro-massa'], function ($elemento) {
    return isset($elemento);
});

$mostrar_opcoes_registro = !empty($opcoes_registro);
$mostrar_opcoes_registro_massa = !empty($opcoes_registro_massa);
$tem_id = array_key_exists($this->traduzir('ID'), $params['lista'][0]);
?>

[DLX-CONTEUDO]
<form id="form-lista" method="post" action="<?php echo $params['html:form-acao'] ?>">
    <?php
    if (array_key_exists('lista', $params) && !empty($params['lista'])) {
        echo HTMLLista::inicioLista('registros');
        echo HTMLLista::subtitulo(sprintf($this->traduzir('Mostrando %d registros de um total de %d encontrados.', 'painel-dlx'), $params['info:qtde-registros-exibidos'], $params['info:qtde-total-registros']));

        # Cabeçalho ----------------------------------------------------------------------------------------------------
        echo HTMLLista::inicioCabecalho();
        echo HTMLLista::inicioLinha();

        if ($tem_id) {
            echo HTMLLista::celulaTitulo('chk', '<input type="checkbox" onclick="listaRegistros.marcarTodasLinhas(this.checked, $(this).parents(\'form\'))"/>', ['class' => 'dado -chk']);
        } // Fim if

        foreach (array_keys($params['lista'][0]) as $titulo) {
            if (!$mostrar_id && $titulo === $this->traduzir('ID')) {
                continue;
            } // Fim if

            echo HTMLLista::celulaTitulo(
                $titulo, $titulo,
                $titulo === $this->traduzir('ID') ? ['class' => 'dado -id'] : []
            );
        } // Fim foreach

        if ($mostrar_opcoes_registro && $tem_id) {
            echo HTMLLista::celulaTitulo($this->traduzir('Opções'), $this->traduzir('Opções'), ['class' => 'dado -opcoes']);
        } // Fim if

        echo HTMLLista::fimLinha();
        echo HTMLLista::fimCabecalho();

        # Conteúdo -----------------------------------------------------------------------------------------------------
        echo HTMLLista::inicioConteudo();

        foreach ($params['lista'] as $registro) {
            echo HTMLLista::inicioLinha();

            if ($tem_id) {
                echo HTMLLista::celulaComum('chk', '<input type="checkbox" name="id[]" id="idreg-' . $registro[$this->traduzir('ID')] . '" value="' . $registro[$this->traduzir('ID')] . '"/>', ['class' => 'dado -chk']);
            } // Fim if

            foreach ($registro as $titulo => $dado) {
                if ($titulo === $this->traduzir('ID')) {
                    if (!$mostrar_id) {
                        continue;
                    } // Fim if

                    $atrib = ['class' => 'dado -id'];
                } else {
                    $atrib = strpos($dado, '<br') !== false
                        ? ['class' => 'dado -infos']
                        : [];
                } // Fim if

                echo HTMLLista::celulaComum($titulo, $dado, $atrib);
            } // Fim foreach

            if ($mostrar_opcoes_registro && $tem_id) {
                $id_registro = $registro[$this->traduzir('ID')];
                
                echo HTMLLista::celulaComum($this->traduzir('Opções'),
                    HTMLLinks::linkArray($opcoes_registro, function ($html) use ($id_registro, $params) {
                        return str_replace(
                            array_merge(
                                array_map(function ($v) { return ":{$v}"; }, $params['conf:campos-pk']),
                                [':pk', ':id']
                            ),
                            $id_registro,
                            $html
                        );
                    }),
                    ['class' => 'dado -opcoes']
                );
            } // Fim if

            echo HTMLLista::fimLinha();
        } // Fim foreach

        echo HTMLLista::fimConteudo();

        # Rodapé -------------------------------------------------------------------------------------------------------
        echo HTMLLista::inicioRodape();
        echo HTMLLista::inicioLinha(['class' => 'registro -acoes']);

        if ($mostrar_opcoes_registro_massa && $tem_id) {
            echo HTMLLista::celulaComum(
                null,
                HTMLLinks::linkArray($opcoes_registro_massa),
                ['colspan' => count($params['lista'][0])]
            );
        } // Fim if

        echo HTMLLista::fimLinha();
        echo HTMLLista::fimRodape();

        echo HTMLLista::fimLista();
    } else {
        echo '<p class="sem-registros">', $this->traduzir('Nenhum registro foi encontrado.'), '</p>';
    } // Fim if ... else ?>
</form>

<div id="paginacao"></div>
[/DLX-CONTEUDO]

