<?php
/**
 * Created by PhpStorm.
 * User: dlepera
 * Date: 11/02/16
 * Time: 17:53
 */

use DLX\Ajudantes\HTMLForm;

if (!isset($params)) {
    $params = $this->obterParams();
} // Fim if

define('HTML_MENU_LINK', '<a href="%s" class="link">%s</a>')
?>

[DLX-MENU]
<?php if (count($params['html:itens-menu']) > 0) : ?>
    <ul class="menu-principal">
        <?php foreach ($params['html:itens-menu'] as $item_menu) :
            // Caso o link desse item de menu seja vazio ou 'javascript:' ou # e esse item não tenha
            // sum-menu, ele não deverá ser mostrado.
            if (preg_match('~^(javascript:;?|#)$~', $item_menu['LINK']) && !array_key_exists('SUBMENU', $item_menu)) continue; ?>
            <li class="item">
                <?php printf(HTML_MENU_LINK, $item_menu['LINK'], $item_menu['TEXTO']);
                
                if (array_key_exists('SUBMENU', $item_menu)) : ?>
                    <ul class="sub-menu">
                        <?php foreach ($item_menu['SUBMENU'] as $item_submenu) : ?>
                            <li class="item">
                                <?php
                                    printf(HTML_MENU_LINK, $item_submenu['LINK'], $item_submenu['TEXTO']);
                                    printf('<span class="descr">%s</span>', $item_submenu['DESCR'])
                                ?>
                            </li>
                        <?php endforeach ?>
                    </ul>
                <?php endif ?>
            </li>
        <?php endforeach ?>
    </ul>
<?php endif ?>
[/DLX-MENU]
