<?php
/**
 * painel-dlx
 * @version: v1.17.08
 * @author: Diego Lepera
 *
 * Created by Diego Lepera on 2017-07-28. Please report any bug at
 * https://github.com/dlepera88-php/painel-dlx/issues
 *
 * The MIT License (MIT)
 * Copyright (c) 2017 Diego Lepera http://diegolepera.xyz/
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is furnished
 * to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

use DLX\Ajudantes\Sessao;

if (!isset($params)) {
    $params = $this->obterParams();
} // Fim if
?>

[DLX-MENU-TOPO]
<div class="menu-usuario">
    <a href="javascript:" id="lk-menu-usuario" class="icone"></a>

    <div class="opcoes-usuario">
        <div class="infos">
            <p class="texto">
                <?php echo Sessao::dadoSessao('usuario_nome', FILTER_SANITIZE_STRING), '<br/>',
                    Sessao::dadoSessao('grupo_usuario_nome', FILTER_SANITIZE_STRING) ?>
            </p>

            <?php if (Sessao::dadoSessao('usuario_id', FILTER_VALIDATE_INT, 0) > 0) : ?>
                <p class="links">
                    <a href="admin/usuarios/minha-conta" class="com-icone -botao -minha-conta"><?php echo $this->traduzir('Minha conta', 'painel-dlx') ?></a>
                    <a href="admin/usuarios/alterar-minha-senha" class="com-icone -botao -senha"><?php echo $this->traduzir('Alterar minha senha', 'painel-dlx') ?></a>
                </p>
            <?php endif ?>
        </div>

        <div class="logout">
            <a href="javascript:encerrarSessao()" rel="nofollow" data-ajax-msg="<?php echo $this->traduzir('Encerrando a sessão... Por favor aguarde.', 'painel-dlx') ?>" class="lklogout">
                <?php echo $this->traduzir('Sair', 'painel-dlx') ?>
            </a>
        </div>
    </div>
</div>
[/DLX-MENU-TOPO]
