<?php
/**
 * MIT License
 *
 * Copyright (c) 2018 PHP DLX
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NON INFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

use Vilex\Templates\AbstractTemplate;

/** @var AbstractTemplate $this */
?>

[CORPO]
<form id="form-reset-senha" method="post" action="/painel-dlx/reset-senha/solicitar" class="form-reset-senha">
    <h1 class="titulo-pagina"><?php echo $this->getAtributo('titulo-pagina') ?></h1>

    <p class="mensagem-usuario -info">
        Para recuperar sua senha, informe o seu email cadastrado no sistema, que será onde receberá as informções para
        recuperação da senha.
    </p>

    <p class="form-paragr">
        <label for="email" class="form-rotulo form-controle-email">Email</label>
        <input type="email" name="email" id="email" class="form-controle" required>
    </p>

    <p class="form-botoes">
        <button type="submit" class="botao-reset-senha" data-ajax-msg="Enviando email de recuperação da senha...<br>Por favor, aguarde um instante.">
            Recuperar senha
        </button>
    </p>
</form>
[/CORPO]

[SCRIPTS]
<script>
    $('#form-reset-senha').formAjax({
        func_depois: function(json, status, xhr) {
            if (json.retorno === 'sucesso') {
                msgUsuario.adicionar(json.mensagem, json.retorno, xhr.id);
                window.location = '/';
            }

            msgUsuario.mostrar(json.mensagem, json.retorno, xhr.id);
        }
    });
</script>
[/SCRIPTS]