<?php
/**
 * painel-dlx
 * @version: v1.17.08
 * @author: Diego Lepera
 *
 * Created by Diego Lepera on 2017-07-28. Please report any bug at
 * https://github.com/dlepera88-php/painel-dlx/issues
 *
 * The MIT License (MIT)
 * Copyright (c) 2017 Diego Lepera http://diegolepera.xyz/
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is furnished
 * to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

if (!isset($params)) {
    $params = $this->obterParams();
} // Fim if

$ckeditor = (array)$params['conf:ckeditor-id'];
?>

[DLX-SCRIPTS]
<script>
    //<![CDATA[
    CKEDITOR.stylesSet.add('default', [
        { name: 'Título 1', element: 'h1', attributes: { 'class': 'titulo-h1' } },
        { name: 'Título 2', element: 'h2', attributes: { 'class': 'titulo-h2' } }
    ]);
    CKEDITOR.config.extraPlugins = 'uploadfile,uploadimage,uploadwidget,filetools,lineutils,notification,notificationaggregator,widget,widgetselection,filebrowser,popup';
    CKEDITOR.config.uploadUrl = '../ap-global/ckeditor/upload-arquivos/copia-e-cola';
    // Turn off automatic editor creation first.
    CKEDITOR.disableAutoInline = true;

    <?php if (count($ckeditor) > 0) :
        $form = array_key_exists('html:form-id', $params) ? "#form-{$params['html:form-id']}" : 'form';
        // $upload = "{$params['config-aplicativo']['raiz']}ap-global/ckeditor/upload-arquivos/navegador";

        foreach ($ckeditor as $ck) : ?>
            CKEDITOR.replace('<?php echo $ck ?>', {
                // filebrowserUploadUrl: '<?php echo $upload ?>',
                // filebrowserImageUploadUrl: '<?php echo $upload ?>'
            });
        <?php endforeach ?>

        $('<?php echo $form ?>').on('submit.__ckeditor', function () {
            <?php foreach ($ckeditor as $ck) : ?>
                $('#<?php echo $ck ?>').val(
                    $('#cke_<?php echo $ck ?>').find('iframe')
                        .contents().find('[contenteditable]').html()
                );
            <?php endforeach ?>
        });
    <?php endif ?>
    //]]>
</script>
[/DLX-SCRIPTS]
