<?php
/**
 * painel-dlx
 * @version: v1.17.08
 * @author: Diego Lepera
 *
 * Created by Diego Lepera on 2017-07-28. Please report any bug at
 * https://github.com/dlepera88-php/framework-dlx/issues
 *
 * The MIT License (MIT)
 * Copyright (c) 2017 Diego Lepera http://diegolepera.xyz/
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is furnished
 * to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

use DLX\Ajudantes\Strings;

if (!isset($params)) {
    $params = $this->obterParams();
} // Fim if

$usuario = $params['modelo'];
?>

[DLX-CONTEUDO]
<details class="mostrar-detalhes" open>
    <summary class="det-titulo"><?php echo $this->traduzir('Dados pessoais', 'painel-dlx') ?></summary>

    <p class="det-paragr">
        <span class="det-rotulo"><?php echo $this->traduzir('Nome', 'painel-dlx') ?></span>
        <?php echo $usuario->getNome(); ?>
    </p>

    <p class="det-paragr">
        <span class="det-rotulo"><?php echo $this->traduzir('E-mail', 'painel-dlx') ?></span>
        <?php echo $usuario->getEmail() ?>
    </p>
</details>

<details class="mostrar-detalhes" open>
    <summary class="det-titulo"><?php echo $this->traduzir('Preferências', 'painel-dlx') ?></summary>

    <p class="det-paragr">
        <span class="det-rotulo"><?php echo $this->traduzir('Idioma', 'painel-dlx') ?></span>
        <?php echo $params['info:idioma'] ?>
    </p>

    <p class="det-paragr">
        <span class="det-rotulo"><?php echo $this->traduzir('Tema', 'painel-dlx') ?></span>
        <?php echo $params['info:tema'] ?>
    </p>

    <p class="det-paragr">
        <span class="det-rotulo"><?php echo $this->traduzir('Formato de data', 'painel-dlx') ?></span>
        <?php echo $params['info:formato-data'] ?>
    </p>
</details>

<details class="mostrar-detalhes" open>
    <summary class="det-titulo"><?php echo $this->traduzir('Acesso sistema', 'painel-dlx') ?></summary>

    <p class="det-paragr">
        <span class="det-rotulo"><?php echo $this->traduzir('Login', 'painel-dlx') ?></span>
        <?php echo $usuario->getLogin() ?>
    </p>

    <?php if ($params['conf:alterar-senha?']) : ?>
        <a href="admin/usuarios/alterar-minha-senha" class="com-icone -botao -editar">
            <?php echo $this->traduzir('Alterar minha senha', 'painel-dlx') ?>
        </a>
    <?php endif ?>
</details>

<details class="mostrar-detalhes" open>
    <summary class="det-titulo"><?php echo $this->traduzir('Configurações', 'painel-dlx') ?></summary>

    <p class="det-paragr">
        <span class="det-rotulo"><?php echo $this->traduzir('Grupo', 'painel-dlx') ?></span>
        <?php echo $params['info:grupo-usuario'] ?>
    </p>

    <p class="det-paragr">
        <span class="det-rotulo"><?php echo $this->traduzir('Está bloqueado?', 'painel-dlx') ?></span>
        <?php echo Strings::bool2humano($usuario->isBloqueado()) ?>
    </p>

    <?php if (!$params['conf:usuario-dominio?']) : ?>
        <p class="det-paragr">
            <span class="det-rotulo"><?php echo $this->traduzir('Deve resetar a senha no próximo login?', 'painel-dlx') ?></span>
            <?php echo Strings::bool2humano($usuario->isResetSenha()) ?>
        </p>
    <?php endif ?>
</details>
[/DLX-CONTEUDO]
