<?php
/**
 * painel-dlx
 * @version: v1.17.08
 * @author: Diego Lepera
 *
 * Created by Diego Lepera on 2017-07-28. Please report any bug at
 * https://github.com/dlepera88-php/painel-dlx/issues
 *
 * The MIT License (MIT)
 * Copyright (c) 2017 Diego Lepera http://diegolepera.xyz/
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is furnished
 * to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

use \DLX\Ajudantes\HTMLForm;

if (!isset($params)) {
    $params = $this->obterParams();
} // Fim if

$config_email = $params['modelo'];
?>

[DLX-CONTEUDO]
<form id="form-<?php echo $params['html:form-id'] ?>" action="<?php echo $params['html:form-acao'] ?>" method="post" data-url-detalhes="<?php echo $params['conf:form-url-lista'] ?>" data-url-editar="<?php echo $params['conf:form-url-editar'] ?>">
    <fieldset class="form-grupo">
        <legend class="form-legenda"><?php echo $this->traduzir('Geral', 'painel-dlx') ?></legend>

        <p class="form-paragr">
            <?php echo HTMLForm::campoGeral('texto', 'servidor', 'servidor', $config_email->getServidor(), $this->traduzir('Servidor SMTP', 'painel-dlx'), null, [
                'maxlength'   => 80,
                'placeholder' => $this->traduzir('Ex.: smtp.dominio.com.br', 'painel-dlx'),
                'required'    => 'required'
            ]), ':', HTMLForm::campoGeral('numero', 'porta', 'porta', $config_email->getPorta(), null, null, [
                'min'      => 1, 'max' => 65535,
                'required' => 'required'
            ]) ?>
        </p>

        <p class="form-paragr">
            <?php echo HTMLForm::comboSelect('cripto', 'cripto', $config_email->getCripto(), $this->traduzir('Criptografia', 'painel-dlx'), null, [], [
                ['VALOR' => '', 'TEXTO' => $this->traduzir('Nenhuma', 'painel-dlx')],
                ['VALOR' => 'ssl', 'TEXTO' => $this->traduzir('SSL', 'painel-dlx')],
                ['VALOR' => 'tls', 'TEXTO' => $this->traduzir('TLS', 'painel-dlx')]
            ]) ?>
        </p>
    </fieldset>

    <fieldset class="form-grupo">
        <legend class="form-legenda"><?php echo $this->traduzir('Autenticação', 'painel-dlx') ?></legend>

        <p class="form-paragr">
            <?php echo HTMLForm::chkSimNao('autent', 'autent', $config_email->isAutent(), $this->traduzir('Requer autenticação?', 'painel-dlx')) ?>
        </p>

        <p id="autent-conta" class="form-paragr">
            <?php echo HTMLForm::campoGeral('texto', 'conta', 'conta', $config_email->getConta(), $this->traduzir('Conta', 'painel-dlx'), null, [
                'maxlength' => 100
            ]) ?>
        </p>

        <p id="autent-senha" class="form-paragr">
            <?php echo HTMLForm::campoGeral('senha', 'senha', 'senha', '*****', $this->traduzir('Senha', 'painel-dlx'), null, [
                'maxlength' => 100
            ]) ?>
        </p>
    </fieldset>

    <fieldset class="form-grupo">
        <legend class="form-legenda"><?php echo $this->traduzir('Configurações', 'painel-dlx'); ?></legend>

        <p class="form-paragr">
            <?php echo HTMLForm::campoGeral('texto', 'de_nome', 'de-nome', $config_email->getDeNome(), $this->traduzir('De (nome)', 'painel-dlx')) ?>
        </p>

        <p class="form-paragr">
            <?php echo HTMLForm::campoGeral('email', 'responder_para', 'responder-para', $config_email->getResponderPara(), $this->traduzir('Responder para', 'painel-dlx')) ?>
        </p>

        <p class="form-paragr">
            <?php echo HTMLForm::chkSimNao('html', 'html', $config_email->isHtml(), $this->traduzir('Corpo em HTML?', 'painel-dlx')) ?>
        </p>
    </fieldset>

    <p class="form-botoes">
        <?php echo HTMLForm::botao('salvar', $this->traduzir('Salvar', 'painel-dlx')), HTMLForm::botao('cancelar', $this->traduzir('Cancelar', 'painel-dlx')) ?>
    </p>
</form>
[/DLX-CONTEUDO]

[DLX-SCRIPTS]
<script>
    //<![[CDATA
    $('#chk-autent').on('change.__script', function () {
        var $autent_infos = $('#autent-conta, #autent-senha');

        $(this).prop('checked')
            ? $autent_infos.fadeIn()
            : $autent_infos.fadeOut();
    }).trigger('change.__script');
    //]]>
</script>
[/DLX-SCRIPTS]
