<?php
/**
 * MIT License
 *
 * Copyright (c) 2018 PHP DLX
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NON INFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

use PainelDLX\Domain\CadastroUsuarios\Entities\GrupoUsuario;
use PainelDLX\Domain\CadastroUsuarios\Entities\Usuario;
use Vilex\VileX;

/**
 * @var VileX $this
 */

/** @var Usuario $usuario */
$usuario = $this->getAtributo('usuario');
?>

[CORPO]
<h1 class="titulo-pagina"><?php echo $this->getAtributo('titulo-pagina') ?></h1>

<div class="layout-barra-lateral">
    <?php include 'menu_lateral_usuarios.phtml' ?>

    <div class="detalhe-usuario">
        <details id="dados-pessoais" class="detalhe-registro" open>
            <summary class="detalhe-registro-titulo">Dados Pessoais</summary>

            <p class="detalhe-registro-paragr">
                <span class="detalhe-registro-rotulo">Nome:</span>
                <?php echo $usuario->getNome() ?>
            </p>

            <p class="detalhe-registro-paragr">
                <span class="detalhe-registro-rotulo">Email:</span>
                <?php echo $usuario->getEmail() ?>
            </p>
        </details>

        <?php if ($this->getAtributo('is-usuario-logado')) : ?>
        <details id="acesso-sistema" class="detalhe-registro" open>
            <summary class="detalhe-registro-titulo">Acesso ao sistema</summary>

            <p class="detalhe-registro-paragr">
                <a href="alterar-minha-senha" class="btn btn-alterar-senha">
                    Alterar senha
                </a>
            </p>
        </details>
        <?php endif ?>

        <details id="grupos-usuarios" class="detalhe-registro" open>
            <summary class="detalhe-registro-titulo">Grupos de Usuários</summary>

            <ul>
                <?php
                /** @var GrupoUsuario $grupo_usuario */
                foreach ($usuario->getGrupos() as $grupo_usuario) : ?>
                    <li class="detalhe-registro-paragr">
                        <?php echo $grupo_usuario->getNome() ?>
                    </li>
                <?php endforeach; ?>
            </ul>
        </details>
    </div>
</div>
[/CORPO]